<?php
/*
$meniny=array
( "nikto", "Alexandra", "Daniela", "Drahoslav", "Andrea", "Antónia", "Bohuslava", "Severín", "Alexej", "Dáša", "Malvína", "Ernest", "Rastislav", "Radovan", "Dobroslav", "Kristína", "Nataša", "Bohdana", "Drahomíra, Mário", "Dalibor", "Vincent", "Zora", "Miloš", "Timotej", "Gejza", "Tamara", "Bohuš", "Alfonz", "Gašpar", "Ema", "Emil", "Tatiana", "Erik, Erika", "Blažej", "Veronika", "Agáta", "Dorota", "Vanda", "Zoja", "Zdenko", "Gabriela", "Dezider", "Perla", "Arpád", "Valentín", "Pravoslav", "Ida", "Miloslava", "Jaromír", "Vlasta", "Lívia", "Eleonóra", "Etela", "Roman, Romana", "Matej", "Frederik, Frederika", "Viktor", "Alexander", "Zlatica", "Radomír, Radomíra", "Albín", "Anežka", "Bohumil, Bohumila", "Kazimír", "Fridrich", "Radoslav, Radoslava", "Tomáš", "Alan, Alana", "Františka", "Branislav, Bruno", "Angela, Angelika", "Gregor", "Vlastimil", "Matilda", "Svetlana", "Boleslav", "¼ubica", "Eduard", "Jozef", "Víťazoslav", "Blahoslav", "Beòadik", "Adrián", "Gabriel", "Marián", "Emanuel", "Alena", "Soòa", "Miroslav", "Vieroslava", "Benjamín", "Hugo", "Zita", "Richard", "Izidor", "Miroslava", "Irena", "Zoltán", "Albert", "Milena", "Igor", "Július", "Estera", "Aleš", "Justína", "Fedor", "Dana, Danica", "Rudolf", "Valér", "Jela", "Marcel", "Ervín", "Slavomír", "Vojtech", "Juraj", "Marek", "Jaroslava", "Jaroslav", "Jarmila", "Lea", "Anastázia", "nikto", "Žigmund", "Galina", "Florián", "Lesana, Lesia", "Hermína", "Monika", "Ingrida", "Roland", "Viktória", "Blažena", "Pankrác", "Servác", "Bonifác", "Žofia", "Svetozár", "Gizela", "Viola", "Gertrúda", "Bernard", "Zina", "Júlia Juliana", "Želmíra", "Ela", "Urban", "Dušan", "Iveta", "Viliam", "Vilma", "Ferdinand", "Petronela, Petrana", "Žaneta", "Xénia", "Karolína", "Lenka", "Laura", "Norbert", "Róbert", "Medard", "Stanislava", "Margaréta", "Dobroslava", "Zlatko", "Anton", "Vasi¾", "Vít", "Blanka", "Adolf", "Vratislav", "Alfréd", "Valéria", "Alojz", "Paulína", "Sidónia", "Ján", "Tadeáš", "Adriána", "Ladislav, Ladislava", "Beáta", "Peter a Pavol, Petra", "Melánia", "Diana", "Berta", "Miloslav", "Prokop", "nikto", "Patrik, Patrícia", "Oliver", "Ivan", "Lujza", "Amália", "Milota", "Nina", "Margita", "Kamil", "Henrich", "Drahomír", "Bohuslav", "Kamila", "Dušana", "I¾j, Eliáš", "Daniel", "Magdaléna", "Oľga", "Vladimír", "Jakub", "Anna, Hana", "Božena", "Krištof", "Marta", "Libuša", "Ignác", "Božidara", "Gustáv", "Jerguš", "Dominik, Dominika", "Hortenzia", "Jozefína", "Štefánia", "Oskar", "¼ubomíra", "Vavrinec", "Zuzana", "Darina", "¼ubomír", "Mojmír", "Marcela", "Leonard", "Milica", "Elena, Helena", "Lýdia", "Anabela", "Jana", "Tichomír", "Filip", "Bartolomej", "¼udovít", "Samuel", "Silvia", "Augustín", "Nikola, Nikolaj", "Ružena", "Nora", "Drahoslava", "Linda", "Belo", "Rozália", "Regína", "Alica", "Marianna", "Miriama", "Martina", "Oleg", "Bystrík", "Mária", "Ctibor", "¼udomil", "Jolana", "¼udmila", "Olympia", "Eugénia", "Konštantín", "¼uboslav, ¼uboslava", "Matúš", "Móric", "Zdenka", "¼uboš, ¼ubor", "Vladislav", "Edita", "Cyprián", "Václav", "Michal, Michaela", "Jarolím", "Arnold", "Levoslav", "Stela", "František", "Viera", "Natália", "Eliška", "Brigita", "Dionýz", "Slavomíra", "Valentína", "Maximilián", "Koloman", "Boris", "Terézia", "Vladimíra", "Hedviga", "Lukáš", "Kristián", "Vendelín", "Uršuľa", "Sergej", "Alojzia", "Kvetoslava", "Aurel", "Demeter", "Sabína", "Dobromila", "Klára", "Šimon Simona", "Aurélia", "Denis, Denisa", "nikto", "Hubert", "Karol", "Imrich", "Renáta", "René", "Bohumír", "Teodor", "Tibor", "Martin, Maroš", "Svätopluk", "Stanislav", "Irma", "Leopold", "Agnesa", "Klaudia", "Eugen", "Alžbeta", "Félix", "Elvíra", "Cecília", "Klement", "Emília", "Katarína", "Kornel", "Milan", "Henrieta", "Vratko", "Ondrej, Andrej", "Edmund", "Bibiána", "Oldrich", "Barbora", "Oto", "Mikuláš", "Ambróz", "Marína", "Izabela", "Radúz", "Hilda", "Otília", "Lucia", "Branislava, Bronislava", "Ivica", "Albína", "Kornélia", "Sláva, Slávka", "Judita", "Dagmara", "Bohdan", "Adela", "Nadežda", "Adam a Eva", "nikto", "Štefan", "Filoména", "Ivana, Ivona", "Milada", "Dávid", "Silvester", "nikto" );
*/

$meniny=array(
	0	=>	'Nový rok',
	1	=>	'Alexandra, Karina, Ábel, Makar, Karin, Kara, Kasandra, Sanda, Sandra, Saša a Senda',
	2	=>	'Daniela, Danila, Danuta, Genovéva a Radmila',
	3	=>	'Drahoslav, Drahoľub, Drahomil, Drahoň, Drahoš, Duchoslav, León, Títus, Drahoľuba, Drahomila, Duchoslava, Leóna a Leónia',
	4	=>	'Andrea a Artúr',
	5	=>	'Antónia, Melchior, Melichar a Menhard',
	6	=>	'Bohuslava, Atila, Lucián, Bohuna, Boleslava, Božislava a Luciána',
	7	=>	'Severín, Čestmír, Pravomil, Čestmíra, Pravomila a Severína',
	8	=>	'Alexej, Alex, Domoľub, Julián, Pravoľub, Vladan, Vladen, Alexia, Pravoľuba, Vladana a Vladena',
	9	=>	'Dáša, Agatón, Dalimil, Dalimír, Dalimila a Dalimíra',
	10	=>	'Malvína, Honorát, Tasilo a Honoráta',
	11	=>	'Ernest, Arkád, Arnošt, Arkádia, Arnoštka, Erna a Ernestína',
	12	=>	'Rastislav, Čistomil, Čistoslav, Rastic, Rastimír, Ratislav, Vidor, Čistomila, Čistoslava, Rastislava a Ratislava',
	13	=>	'Radovan, Hilár, Uriáš, Uriel, Hilária a Radovana',
	14	=>	'Dobroslav, Dobrotín, Domoslav, Loránt, Múdroslav a Domoslava',
	15	=>	'Kristína',
	16	=>	'Nataša a Antal',
	17	=>	'Bohdana, Priskus, Piroška a Priska',
	18	=>	'Drahomíra, Mário, Sára, Márius a Dúbravka',
	19	=>	'Dalibor, Fabián, Fábius, Sebastián, Šebastián, Fábia, Fabiána, Fabiola a Sebastiána',
	10	=>	'Vincent a Vincencia',
	21	=>	'Zora, Dorián, Sírius, Slavoľub, Slavomil, Zoran, Auróra, Cyntia, Doriána, Sinda, Slavomila a Zorana',
	22	=>	'Miloš, Miloň a Selma',
	23	=>	'Timotej, Ctiboh a Timotea',
	24	=>	'Gejza, Saul a Šavol',
	25	=>	'Tamara, Polykarp, Slavibor, Slavislav, Slaviboj, Slavoboj, Svätoboj, Svätobor, Xenofón, Žarko a Polykarpa',
	26	=>	'Bohuš, Pribislav a Pribiš',
	27	=>	'Alfonz, Manfréd a Alfonzia',
	28	=>	'Gašpar a Pribina',
	29	=>	'Ema a Jasna',
	30	=>	'Emil, Emilián a Emiliána',
	31	=>	'Tatiana, Hynek, Trifon a Táňa',
	32	=>	'Erik, Erika a Aida',
	33	=>	'Blažej, Celerín a Celerína',
	34	=>	'Veronika, Nika, Verena a Verona',
	35	=>	'Agáta, Moderát, Modest, Leda, Moderáta a Modesta',
	36	=>	'Dorota, Dorisa a Titanila',
	37	=>	'Vanda a Romuald',
	38	=>	'Zoja a Aranka',
	39	=>	'Zdenko, Rainold, Rinaldo, Zdeno, Apolena, Apoliena a Apolónia',
	40	=>	'Gabriela, Scholastika a Školastika',
	41	=>	'Dezider, Želislav, Dezidera a Želislava',
	42	=>	'Perla, Ron, Ronald, Zoro, Zoroslav, Eulália, Slavena, Solveiga a Zoroslava',
	43	=>	'Arpád, Jordán a Jordána',
	44	=>	'Valentín a Velimír',
	45	=>	'Pravoslav, Faust, Faustína, Georgia, Georgína a Pravoslava',
	46	=>	'Ida, Liana, Pamfil a Pamfília',
	47	=>	'Miloslava, Flavián, Flávius, Silván, Silvín, Flávia, Milomíra, Miluša a Silvána',
	48	=>	'Jaromír, Simeon, Jaromíra, Konkordia a Bernadetta',
	49	=>	'Vlasta, Konrád a Kurt',
	50	=>	'Lívia, Aladár, Lívio, Lívius, Udo, Ulrich, Alma, Ulrika a Ulriška',
	51	=>	'Eleonóra',
	52	=>	'Etela',
	53	=>	'Roman, Romana a Romina',
	54	=>	'Matej, Jazmína, Goran a Mateja',
	55	=>	'Frederik, Frederika, Taras a Federika',
	56	=>	'Viktor, Porfýr a Edina',
	57	=>	'Alexander, Leander, Sandro, Skender, Drahotína, Dražica a Leandra',
	58	=>	'Zlatica, Elemír, Elo, Lumír a Zlata',
	59	=>	'Radomír a Radomíra',
	60	=>	'Albín',
	61	=>	'Anežka',
	62	=>	'Bohumil, Bohumila, Ticián, Ginda, Kunigunda a Ticiána',
	63	=>	'Kazimír, Gerazim, Romeo, Jadrana a Kazimíra',
	64	=>	'Fridrich, Lucius, Teofil, Friderika a Teofila',
	65	=>	'Radoslav, Radoslava, Fridolín, Koriolán, Radislav, Radovan, Felícia, Fridolína a Radislava',
	66	=>	'Tomáš, Tomislav, Tomáška a Tomislava',
	67	=>	'Alan a Alana',
	68	=>	'Františka a Erhard',
	69	=>	'Branislav, Bruno, Bratislav, Bronislav, Bratislava a Taras',
	70	=>	'Angela, Angelika, Angel, Volfram, Algelína a Jurina',
	71	=>	'Gregor, Teofan, Gregora, Gregoria a Gregorína',
	72	=>	'Vlastimil, Kira a Rozína',
	73	=>	'Matilda a Metaneta',
	74	=>	'Svetlana, Agap, Belomír, Rodan, Roderich, Roderik, Torkvát, Agapa, Agapia, Rodana a Roderika',
	75	=>	'Boleslav, Amos, Bolemír, Heribert a Bolemíra',
	76	=>	'Ľubica, Ľuban, Ľuben, Zbignev, Zbyšek a Ľuba',
	77	=>	'Eduard, Ctislav, Salvátor, Ctislava a Eduarda',
	78	=>	'Jozef a Sibyla',
	79	=>	'Víťazoslav, Klaudián, Klaudín, Klaudio, Klaudius a Víťazoslava',
	80	=>	'Blahoslav, Blahoboj, Blahosej, Radek a Radko',
	81	=>	'Beňadik, Benedikt, Oktavián, Oktávius, Benedikta, Benilda, Benita, Izolda a Oktávia',
	82	=>	'Adrián, Apián, Dárius, Viktorián a Apia',
	83	=>	'Gabriel',
	84	=>	'Marián, Humbert, Anunciáta, Irida a Irisa',
	85	=>	'Emanuel, Eman, Manuel, Emanuela a Manuela',
	86	=>	'Alena, Rupert, Ruprecht a Dita',
	87	=>	'Soňa a Ilarion',
	88	=>	'Miroslav, Mieroslav, Bertold, Bertolda a Mieroslava',
	89	=>	'Vieroslava, Vieroľub, Vieromil a Vieroslav',
	90	=>	'Benjamín, Kvído a Balbína',
	91	=>	'Hugo a Hugolín',
	92	=>	'Zita a Áron',
	93	=>	'Richard a Richarda',
	94	=>	'Izidor a Izidora',
	95	=>	'Miroslava a Mira',
	96	=>	'Irena, Irína, Celestín, Ruben, Sixtus, Celestína a Venuša',
	97	=>	'Zoltán, Armand, Herman, Rufínus, Rúfus, Armanda, Rufína a Rumjana',
	98	=>	'Albert, Albertín, Albrecht, Valter, Alberta, Albertína a Albrechta',
	99	=>	'Milena, Erhard a Mileva',
	100	=>	'Igor, Ezechiel, Ivar, Ivor, Radomil, Igora a Radomila',
	101	=>	'Július, Antip, Ariel, Ariela, Arleta, Leo a Lev',
	102	=>	'Estera, Aster, Davorín, Zenon a Astéria',
	103	=>	'Aleš, Artem, Artemon, Artemia, Artemida a Norma',
	104	=>	'Justína, Hrdoslav, Hrdoš, Justín, Davorína, Hrdoslava a Justa',
	105	=>	'Fedor a Fedora',
	106	=>	'Dana a Danica',
	107	=>	'Rudolf, Ralf, Rolf, Rudolfa a Rudolfína',
	108	=>	'Valér, Apolón, Erich, Verner a Ilma',
	109	=>	'Jela, Krescenc a Krescencia',
	110	=>	'Marcel a Hvezdoň',
	111	=>	'Ervín, Abelard, Adelard, Anzelm, Žitoslav, Anzelma, Ervína, Saskia a Žitoslava',
	112	=>	'Slavomír, Slávo, Tvrdomír, Jelena a Noema',
	113	=>	'Vojtech, Adalbert, Roger, Adalberta, Vojtecha a Vojteška',
	114	=>	'Juraj, Fidél, Gaston, Georg, Helmut, Jorik, Jürgen, Deora, Fidélia, Jorga, Jorika a Juraja',
	115	=>	'Marek, Izmael, Marko a Markus',
	116	=>	'Jaroslava',
	117	=>	'Jaroslav, Aristid, Tulius, Aristída a Tulia',
	118	=>	'Jarmila, Prudencius a Prudencia',
	119	=>	'Lea a Timon',
	110	=>	'Anastázia, Anastáz, Blahomil, Asia, Blahomila, Nasťa a Nastasia',
	121	=>	'Amarila, Pamela a Kevin',
	122	=>	'Žigmund, Atanáz, Atanázia a Aténa',
	123	=>	'Galina, Horác, Desana, Halina a Timea',
	124	=>	'Florián, Flór, Aglája, Floriána, Florína a Pelagia',
	125	=>	'Lesana, Gothard, Pius, Lesia, Pia a Toska',
	126	=>	'Hermína, Ovídius, Radivoj, Tankréd, Elfrída, Frída, Herina a Mineta',
	127	=>	'Monika, Napoleon, Stanimír a Mona',
	128	=>	'Ingrida, Ina a Inga',
	129	=>	'Roland a Rolanda',
	130	=>	'Viktória, Armín, Armína a Beatrica',
	131	=>	'Blažena, Miranda a Svatava',
	132	=>	'Pankrác a Achiles',
	133	=>	'Servác, Chraniboj, Chranibor, Chranislav, Servián, Chranislava, Imelda a Konzuela',
	134	=>	'Bonifác',
	135	=>	'Žofia, Brenda, Raisa, Sofia a Zosia',
	136	=>	'Svetozár, Peregrín a Peregrína',
	137	=>	'Gizela, Andronik, Ditmar, Paskal, Andronika a Paskália',
	138	=>	'Viola',
	139	=>	'Gertrúda a Gerda',
	140	=>	'Bernard, Bernardín, Hviezdoslav, Bernadeta, Bernarda, Bernardína a Hviezdoslava',
	141	=>	'Zina, Dobromír, Hostimil, Hostirad, Hostislav, Hostisvit, Teobald, Dobromíra, Hostimila a Hostislava',
	142	=>	'Júlia, Juliána, Liana a Rita',
	143	=>	'Želmíra, Želmír a Želimír',
	144	=>	'Ela',
	145	=>	'Urban, Vselovod, Vševlad a Vanesa',
	146	=>	'Dušan',
	147	=>	'Iveta, Vadim, Valdemar a Valdemara',
	148	=>	'Viliam, Vilhelm, Elektra, Elma a Vilhelmína',
	149	=>	'Vilma, Elmar, Maxim a Maxima',
	150	=>	'Ferdinand, Neander a Ferdinanda',
	151	=>	'Petrana, Petronela, Petrónius, Blahoslav, Nela, Petrónia a Nelly',
	152	=>	'Žaneta',
	153	=>	'Oxana, Xénia, Erazim, Erazmus, Jaromil a Vlastimila',
	154	=>	'Karolína, Kevin, Lino, Linus, Palmíro, Kaja, Klotilda, Lina, Lineta a Palmíra',
	155	=>	'Lenka a Lena',
	156	=>	'Laura, Dorotej, Fatima, Laurencia, Loreta a Loriána',
	157	=>	'Norbert, Norman, Romulus, Adolfína, Norberta a Perzida',
	158	=>	'Róbert, Borislav, Robin, Teodot, Dalma, Oriána, Róberta a Robina',
	159	=>	'Medard',
	160	=>	'Stanislava, Felicián, Prímus, Vojeslav, Berenika a Vojeslava',
	161	=>	'Margaréta a Gréta',
	162	=>	'Dobroslava, Barnabáš, Dobrava, Dobrota, Dobrotína, Flóra a Pavoslava',
	163	=>	'Zlatko, Svätoslav, Svetislav, Svetoslav, Zlatan, Zlatomír, Zlatoň, Zlatoš, Svätoslava, Svetislava, Svetoslava, Zlatana a Zlatomíra',
	164	=>	'Anton, Genadij a Tobiáš',
	165	=>	'Vasil, Bazil, Elizej, Kvintilián, Kvintín, Kvintus, Herta, Kvinta a Kvintiliána',
	166	=>	'Vít a Jolana',
	167	=>	'Bianka, Blanka, Benon, Božetech, Alina a Božetecha',
	168	=>	'Adolf a Adolfína',
	169	=>	'Vratislav, Leontín, Milovan, Milovín, Sedrik, Leontína a Milovana',
	170	=>	'Alfréd, Leonid, Leonídas, Leoš, Ruslan a Alfréda',
	171	=>	'Valéria, Florencián, Florentín, Silver, Florencia a Florentína',
	172	=>	'Alojz, Elvis a Lejla',
	173	=>	'Paulína, Achác, Eberhard, Paulín, Paula, Rozvita a Zaira',
	174	=>	'Sidónia a Sidón',
	175	=>	'Ján, Janis, Jaško, Jens, Johan, Jovan, Nino a Sean',
	176	=>	'Tadeáš, Olívia, Olívius, Prosper, Febrónia a Oliva',
	177	=>	'Adriána, Stojan, Adriena, Ria, Riana a Stojana',
	178	=>	'Ladislav, Ladislava, Samson a Sulamita',
	179	=>	'Beáta, Beátus, Slavoj a Bea',
	180	=>	'Peter, Pavol, Petra, Pavel, Pavla a Petula',
	181	=>	'Melánia, Vlastibor, Vlastimír, Šárka a Vlastimíra',
	182	=>	'Diana, Dean, Dejan, Dina, Zian, Dajana, Deana, Kalina, Tabita, Tajana a Annamária',
	183	=>	'Berta, Bertín a Bertína',
	184	=>	'Miloslav, Irenej, Miliduch, Milomír, Milorad, Radimír, Rodimír a Radimíra',
	185	=>	'Prokop, Procius a Prokopa',
	186	=>	'Cyril, Metod, Cyrus a Cyrila',
	187	=>	'Patrik, Patrícia a Patrokles',
	188	=>	'Oliver, Donald, Kastor, Veleslav, Velislav, Valibals, Veleslava a Velislava',
	189	=>	'Ivan, Ivo, Kilián a Perikles',
	190	=>	'Lujza, Lukrécius, Lizelota a Lukrécia',
	191	=>	'Amália, Amína a Lada',
	192	=>	'Milota a Milutín',
	193	=>	'Nina, Fortunát a Fortunáta',
	194	=>	'Margita, Arne, Borivoj a Merkéta',
	195	=>	'Kamil',
	196	=>	'Henrich, Egon, Enrik, Enriko, Henrik, Henrika, Lota a Šarlota',
	197	=>	'Drahomír, Karmela, Karmen, Karmena, Rút a Rúta',
	198	=>	'Bohuslav, Božislav a Svorad',
	199	=>	'Kamila',
	200	=>	'Dušana',
	201	=>	'Eliáš, Iľja, Ilia, Eliána a Iliana',
	202	=>	'Daniel, Dan a Dalina',
	203	=>	'Magdaléna, Magda, Mahuliena a Majda',
	204	=>	'Oľga, Apolinár, Libérius, Libor, Liborius, Apolinára, Libora a Lilien',
	205	=>	'Vladimír a Kinga',
	206	=>	'Jakub a Žakelína',
	207	=>	'Anna, Hana, Aneta, Anica, Anita, Annamária a Naneta',
	208	=>	'Božena, Gorazd a Pantaleon',
	209	=>	'Krištof, Inocent, Svätomír, Svätoš, Inocencia, Nausika a Svätomíra',
	210	=>	'Marta, Olaf, Serafín, Serafa a Serafína',
	211	=>	'Libuša, Abdon, Ingemar, Ingeborga, Ľubuša a Rowena',
	212	=>	'Ignác, Ignát, Vatroslav a Ignácia',
	213	=>	'Božidara, Božidar, Ľudomír, Božica, Kleopatra, Ľudomíra a Penelopa',
	214	=>	'Gustáv a Gustáva',
	215	=>	'Jerguš, Nikodém a Nikodéma',
	216	=>	'Dominik, Dominika, Krasoslav, Rainer a Krasoslava',
	217	=>	'Hortenzia, Hortenz, Milivoj, Osvald a Snežana',
	218	=>	'Jozefína, Nehoslav a Jozefa',
	219	=>	'Štefánia, Kajetán, Afra, Afrodita, Kajetána a Štefana',
	210	=>	'Oskár, Donát, Hartvig, Virgín, Donáta a Virgínia',
	221	=>	'Ľubomíra a Rastic',
	222	=>	'Vavrinec, Lars, Laurenc, Laurus, Lorenc a Vavro',
	223	=>	'Zuzana, Trojan, Dulcia, Dulcinela a Dulcínia',
	224	=>	'Darina, Dárius a Dária',
	225	=>	'Ľubomír, Hypolit, Kasián, Kasius a Belinda',
	226	=>	'Mojmír, Eusébius, Mojtech a Eusébia',
	227	=>	'Marcela',
	228	=>	'Leonard, Jáchim, Joachim, Linhart, Rochus a Leonarda',
	229	=>	'Milica, Bertram, Bertrand, Hyacint, Libert, Mirón a Hyacinta',
	230	=>	'Elena, Helena a Ilona',
	231	=>	'Lýdia a Vratislava',
	232	=>	'Anabela a Arabela',
	233	=>	'Jana, Johana a Jovana',
	234	=>	'Tichomír, Sigfríd, Tichomil a Tichomíra',
	235	=>	'Filip, Vlastislav, Filipa, Filipína a Vlastislava',
	236	=>	'Bartolomej a Bartolomea',
	237	=>	'Ľudovít, Ludvig, Radim a Ľudovíta',
	238	=>	'Samuel, Samo, Zemfír, Samuela, Tália a Zemfíra',
	239	=>	'Silvia, Silvio a Silvius',
	240	=>	'Augustín, August, Augusta, Augustína a Gustína',
	241	=>	'Nikola, Nikolaj, Koleta a Nikoleta',
	242	=>	'Ružena a Ružica',
	243	=>	'Nora, Rajmund, Ramón, Rajmunda a Ramona',
	244	=>	'Drahoslava, Egid a Egídius',
	245	=>	'Linda, Absolón, Axel, Justus, Ermelinda, Melinda a Rebeka',
	246	=>	'Belo, Antim a Klélia',
	247	=>	'Rozália, Kandid, Mojžiš, Rozalín, Rozálio, Kandida, Róza, Rozeta, Rozita a Rusalka',
	248	=>	'Regína, Bojan, Bojimír, Bojislav, Borimír, Branimír, Chotimír, Justinián, Otakar, Regan, Regulus, Viktorín, Bojana, Bojimíra, Boislava, Branimíra, Budislava, Chotimíra a Larisa',
	249	=>	'Alica, Brian, Magnus, Mansvét, Zachariáš a Bria',
	250	=>	'Marianna a Mariana',
	251	=>	'Miriama a Miriana',
	252	=>	'Martina, Gordan, Gordián, Gordon, Omar, Gordana, Rea a Tina',
	253	=>	'Oleg, Honór, Vitold, Honóra, Krasava a Vitolda',
	254	=>	'Bystrík, Prótus, Zdislav, Helga a Zdislava',
	255	=>	'Mária, Maja, Manon, Manona, Marica, Mariela, Marieta, Marika, Marila, Mariola, Marlena a Marusia',
	256	=>	'Ctibor, Amát, Amátus, Stibor, Sven, Amáta a Tobias',
	257	=>	'Ľudomil, Dragan, Dragutín, Drahan, Drahotín, Ľudomila, Radka a Serena',
	258	=>	'Jolana, Melisa a Melita',
	259	=>	'Ľudmila a Duňa',
	260	=>	'Olympia, Lambert a Záviš',
	261	=>	'Eugénia a Ariadna',
	262	=>	'Konštantín, Trofín, Konstancia a Konštantína',
	263	=>	'Ľuboslav, Ľuboslava, Eustach, Filibert, Liboslav, Eustachia a Liboslava',
	264	=>	'Matúš, Ifigénia a Mirela',
	265	=>	'Móric, Maurícius a Maurus',
	266	=>	'Zdenka, Polyxénia, Tekla a Zdena',
	267	=>	'Ľubor, Ľuboš a Terenc',
	268	=>	'Vladislav, Vladivoj, Eufrozina, Fruzína a Vladislava',
	269	=>	'Edita',
	270	=>	'Cyprián, Damián, Kozmas, Damiána a Mirabela',
	271	=>	'Václav, Chariton, Kariton a Václava',
	272	=>	'Michal, Michaela, Michael a Michala',
	273	=>	'Jarolím, Hieronym, Jeremiáš, Jarolíma, Ráchel, Ráchela a Una',
	274	=>	'Arnold, Remig, Remus, Arnolda a Belina',
	275	=>	'Levoslav, Leodegar a Levoslava',
	276	=>	'Stela, Amadeus, Evald a Amadea',
	277	=>	'František, Edvin a Fraňo',
	278	=>	'Viera, Blahomír, Placid, Blahomíra, Karitína a Placida',
	279	=>	'Natália',
	280	=>	'Eliška',
	281	=>	'Brigita, Brit a Brita',
	282	=>	'Dionýz a Dionýzia',
	283	=>	'Slavomíra, Gedeon, Záboj a Krasomila',
	284	=>	'Valentína, Belín, Zvonimír, Zvonislav, Bruna, Brunhilda, Luneta, Selena, Zvonimíra a Zvonislava',
	285	=>	'Maximilián, Max a Maximiliána',
	286	=>	'Koloman a Edgar',
	287	=>	'Boris, Borislav, Kalist, Borislava a Kalista',
	288	=>	'Terézia a Tereza',
	289	=>	'Vladimíra, Gál, Havel a Havla',
	290	=>	'Hedviga a Jadviga',
	291	=>	'Lukáš',
	292	=>	'Kristián, Christián, Izák, Christiána a Kristiána',
	293	=>	'Vendelín, Eunika a Vendelína',
	294	=>	'Uršuľa, Anatol, Anatólia a Antília',
	295	=>	'Sergej, Dobromil, Sergius, Zdravomil, Kordula, Korduľa, Pribislava, Saloma, Saloména a Solomia',
	296	=>	'Alojzia a Žitomír',
	297	=>	'Kvetoslava, Aretas, Cvetan, Gilbert, Harold, Herald, Krasomil, Kvetoň, Kvetoslav, Rafael, Šalamún, Areta, Cvetana, Gilberta, Kveta, Kvetana, Kvetava a Rafaela',
	298	=>	'Aurel, Krišpín, Vojmír, Zosim, Živan, Živko, Dália, Vojmíra, Živa a Živana',
	299	=>	'Demeter, Amand, Dimitrij, Evarist, Amanda a Demetria',
	300	=>	'Sabína, Horislav, Hromislav, Horislava, Hromislava, Sabrina, Zoa a Zoana',
	301	=>	'Dobromila, Júda a Judáš',
	302	=>	'Klára, Narcis, Zenob, Klarisa, Narcisa, Zenóbia a Kiara',
	303	=>	'Šimon, Simona, Arzen, Asen, Simon, Asena, Simoneta a Šimona',
	304	=>	'Aurélia, Stacho a Volfgang',
	305	=>	'Denis a Denisa',
	306	=>	'Cézar a Cezária',
	307	=>	'Hubert',
	308	=>	'Karol, Džesika, Jesika, Karola a Skarleta',
	309	=>	'Imrich, Emerich a Imriška',
	310	=>	'Renáta, Renát, Renáto a Renátus',
	311	=>	'René a Engelbert',
	312	=>	'Bohumír a Bohumíra',
	313	=>	'Teodor, Orest, Teo, Teodorik, Teodoz, Deodata, Tea, Teodora a Teodózia',
	314	=>	'Tibor, Tiber, Meluzína a Tibora',
	315	=>	'Maroš, Martin a Martinián',
	316	=>	'Svätopluk, Astrid, Jonáš a Astrida',
	317	=>	'Stanislav',
	318	=>	'Irma, Juventín, Mladen, Mladoň, Mladotín, Ima, Juventína, Mladena a Mladotína',
	319	=>	'Leopold, Leopolda a Leopoldína',
	310	=>	'Agnesa, Otmar, Agneša a Inéza',
	321	=>	'Klaudia a Klodeta',
	322	=>	'Eugen a Platón',
	323	=>	'Alžbeta, Betina, Elizabeta, Lila, Liliana, Líza, Lili a Lilly',
	324	=>	'Félix, Filemon a Homér',
	325	=>	'Elvíra, Ctirad a Ctirada',
	326	=>	'Cecília, Cecilián a Šejla',
	327	=>	'Klement, Klementín, Kliment, Kolumbín, Klementína a Kolumbína',
	328	=>	'Emília, Milín a Milina',
	329	=>	'Katarína a Katrina',
	330	=>	'Kornel a Valerián',
	331	=>	'Milan, Nestor, Virgil a Milana',
	332	=>	'Henrieta, Gerhard, Tristan, Desdemona a Eta',
	333	=>	'Vratko, Saturnín a Zaida',
	334	=>	'Andrej, Ondrej a Andreas',
	335	=>	'Edmund a Edmunda',
	336	=>	'Bibiána, Budimír, Budislav, Budimíra a Viviána',
	337	=>	'Oldrich, Sofron, Xavér, Sofrónia a Xavéria',
	338	=>	'Barbora, Babeta, Barbara a Barica',
	339	=>	'Oto, Gerald, Otakar, Otokar, Geralda, Geraldína, Jitka, Ota a Sáva',
	340	=>	'Mikuláš, Nikita, Niko, Nikolas, Mikuláška a Nikoleta',
	341	=>	'Ambróz, Amarant, Amaranta a Ambrózia',
	342	=>	'Marína',
	343	=>	'Izabela, Dalila a Leokádia',
	344	=>	'Radúz a Herbert',
	345	=>	'Hilda, Hildegard a Hildegarda',
	346	=>	'Otília, Spiridon, Dília a Odeta',
	347	=>	'Lucia, Rosan, Rosana a Roxana',
	348	=>	'Branislava, Bronislava a Broňa',
	349	=>	'Ivica, Detrich, Radan a Radana',
	350	=>	'Albína, Bela a Teofánia',
	351	=>	'Kornélia, Lazár, Kora a Korina',
	352	=>	'Sláva, Slávka, Gracián, Grácia, Graciána a Slavislava',
	353	=>	'Judita, Abrahám, Mstislav, Neméz, Ita, Mstislava a Neméza',
	354	=>	'Dagmara, Dagmar, Dag, Dagobert, Daga a Damara',
	355	=>	'Bohdan',
	356	=>	'Adela, Ada, Adelaida, Adelgunda, Adelína, Adina a Alida',
	357	=>	'Nadežda a Naďa',
	358	=>	'Adam, Eva, Evamária, Evelína, Gaja, Gajana a Geja',
	359	=>	'1. sviatok vianočný',
	360	=>	'Štefan',
	361	=>	'Filoména a Filomén',
	362	=>	'Ivana, Ivona a Iva',
	363	=>	'Milada, Jonatán, Miladín, Nátan a Natanel',
	364	=>	'Dávid a Lotar',
	365	=>	'Silvester a Horst'
);


$dni=array (
	0	=>	"nedeľa",
	1	=>	"pondelok",
	2	=>	"utorok",
	3	=>	"streda",
	4	=>	"štvrtok",
	5	=>	"piatok",
	6	=>	"sobota",
);

$mesiac=array(
	0	=>	"januára",
	1	=>	"februára",
	2	=>	"marca",
	3	=>	"apríla",
	4	=>	"mája",
	5	=>	"júna",
	6	=>	"júla",
	7	=>	"augusta",
	8	=>	"septembra",
	9	=>	"októbera",
	10	=>	"novembra",
	11	=>	"decembra",
);

$datum=getdate();
$den_v_tyzdni=$datum["wday"];
$mesiac_v_roku=$datum["mon"];
$p_rok=($datum["year"]);

while ($p_rok > 3)
	{
	$p_rok=$p_rok-4;
	}
if ($p_rok != 0)
{
	if ($datum["yday"]<58)
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+1];
		}
	else
		{
		$meniny_dnes=$meniny[$datum["yday"]+1];
		$meniny_zajtra=$meniny[$datum["yday"]+2];
		}

	if ($datum["mon"]==2 and $datum["mday"]==28)
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+2];
		}
}
else
{
	if ($datum["yday"]<58)
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+1];
		}
	else
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+1];
		}

	if ($datum["mon"]==2 and $datum["mday"]==28)
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+1];
		}
	if ($datum["mon"]==2 and $datum["mday"]==29)
		{
		$meniny_dnes=$meniny[$datum["yday"]];
		$meniny_zajtra=$meniny[$datum["yday"]+1];
		}
}
$dneska = $dni[$den_v_tyzdni] . ',  ' . $datum["mday"] . '. ' . $mesiac[$mesiac_v_roku] . ' ' . $datum["year"];
?>